Added detailed hydra description with OWL and SHACL vocabularies
HydraCG/extensions pull request #17
Opened 2021-07-05 20:18 UTC by alien-mcl

This pull request comes with two minor _extensions_ that adds detailed hydra description created in OWL and SHACL separately.

These two are processed together as both descriptions are comparable and are describing same terms in the similar way.

Feel free to deliberate more on those descriptions.

2021-07-06 09:39 UTC, tpluscode requested changes
I don't like it. It looks like you simply search/replaced the OWL to become SHACL, but shapes would be different, used differently, and serve different purpose than OWL constraints.

I propose we even take a step back there and go class-by-class. As is, the document is a little large to try and review in a meaningful manner. My proposal would be begin with `hydra:ApiDocumentation`'s shape first and follow the vocabulary to add the rest in subsequent PRs

2021-07-06 09:39 UTC, tpluscode commented on hydra-in-owl/hydra_in_owl.ttl
> +@prefix hiowl: <http://www.w3.org/ns/hydra/in-owl#>.
What do you think about using `w3id.org` for all extensions as proposed in #7?

I guess that in this case that would not be in the same namespace as all the rest

2021-07-06 09:39 UTC, tpluscode commented on hydra-in-owl/index.bs
> +     	    "publisher": "W3C"
```suggestion
```

These should be unnecessary. Bikeshed maintains a list of most common standard specification which will link automatically to references

2021-07-06 09:39 UTC, tpluscode commented on hydra-in-shacl/index.bs
> +     	    "publisher": "W3C"
Ditto
```suggestion
```

2021-07-06 13:07 UTC, alien-mcl commented
No - it was not the case. Both OWL and SHACL versions were written from scratch separately, but were put against each other to have i.e. cardinalities in sync.

My entry point was a Hydra rewritten to turtle notation (I'll make a separate PR for that in Specification repo) and then class by class, predicate by predicate both OWL restrictions and SHACL shapes were created. It may look similar though as the order of the terms is the same (due to fact of using same entry point).

I also totaly disagree to move in a PR per term basis - it'll take ages while the task is quite simple. I may consider separating OWL and SHACL though.

2021-07-06 13:09 UTC, alien-mcl commented
BTW, is there any list of valid statuses bikeshed accepts? The spec does not enumerate any and existing specifications are not using two letter derivatives.

2021-07-06 13:11 UTC, tpluscode commented
It is not a simple task, as evidenced by this PR. I cannot really comment on the OWL but there is much to improve in SHACL and it will be much more productive to start small and progress gradually 

I think you're look for https://tabatkins.github.io/bikeshed/#metadata-status

2021-07-06 13:45 UTC, alien-mcl commented
Hmm - I think it's as simple as creating old school pseudo classes, but not with a programming language but with other means. Let us not over-engineer it.

I see that I'll have to make OWL and SHACL separated to make it simpler.

2021-07-10 20:22 UTC, alien-mcl commented
I've moved SHACL to separate PR leaving OWL alone.

2021-07-11 20:10 UTC, alien-mcl commented on hydra-in-owl/hydra_in_owl.ttl
> +@prefix hiowl: <http://www.w3.org/ns/hydra/in-owl#>.
I've switch to w3id.

2021-07-11 20:10 UTC, alien-mcl commented on hydra-in-owl/index.bs
> +     	    "publisher": "W3C"
Removed

2022-01-23 11:30 UTC, tpluscode commented
The changes got lost here too 🤔

2022-03-05 20:39 UTC, alien-mcl commented
Ok - I've recovered all changed files as these were ... ignored :/

2022-10-14 10:15 UTC, tpluscode approved these changes
I think I should "tentatively" approve this. As I said, I feel that this is too big and it's hard to review and verify correctness.

That said I do not intend to actually work on the OWL representation anyway in the foreseeable future...

2022-10-14 10:18 UTC, merged